internalName: vro

locales:
  en:
    name: &bundleName "Võro Keyboards"
    description: "Mobile OS keyboards for the Võro language from the Divvun group at UiT."
  nb:
    name: "Võro tastatur"
    description: "Mobiltastatur for Võro fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

layouts: [vro-mobile, vro-mac, vro-win]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.vro
    icon: images/vro-keyboard-menu-icon.png
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella
    bundleName: *bundleName
    icon: images/Voro_lipp.png

  osx:
    <<: *AppleID
    icon: images/vro-keyboard-menu-icon.png
    version: 0.3.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.2.0
    url: "http://divvun.no"
    uuid: "6D9F0D96-05B8-4F65-AF4B-4378F7580C73"
